<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageVersion>1.0.0-alpha</PackageVersion>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>Lkhsoft.Dring.Shared</Title>
        <Authors>nakira974</Authors>
        <Description>Dring server plugin library</Description>
        <PackageIcon>logo.png</PackageIcon>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/nakira974/Lkhsoft.Dring</RepositoryUrl>
        <PackageProjectUrl>https://github.com/nakira974/Lkhsoft.Dring</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/nakira974/Lkhsoft.Dring/blob/master/Licence</PackageLicenseUrl>
        <PackageTags>dotnet utilities web</PackageTags>
        <PackageReleaseNotes>Created a server plugin library</PackageReleaseNotes>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NLog" Version="5.3.4"/>
        <PackageReference Include="NLua" Version="1.7.3"/>
        <PackageReference Include="System.ComponentModel" Version="4.3.0"/>
        <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0"/>
        <PackageReference Include="System.ComponentModel.Composition" Version="9.0.1"/>
        <PackageReference Include="System.Composition" Version="9.0.1"/>
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.1"/>
    </ItemGroup>

    <ItemGroup>
      <None Remove="logo.png" />
    </ItemGroup>

    <ItemGroup>
        <None Include="logo.png" Pack="true" PackagePath="/" />
    </ItemGroup>
    
</Project>
