name: Server's plugins NuGet package publish

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: [ "trunk", "dev" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore --configfile ./NuGet.Config

      - name: Build
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            dotnet build --configuration Debug --no-restore
          else
            dotnet build --configuration Release --no-restore
          fi

      - name: Package NuGet
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            dotnet pack Lkhsoft.Dring.Shared\Lkhsoft.Dring.Shared.csproj \
              --configuration Debug \
              -o:package \
              -p:VersionSuffix=prerelease
          else
            dotnet pack Lkhsoft.Dring.Shared\Lkhsoft.Dring.Shared.csproj \
              --configuration Release \
              -o:package
          fi

      - name: Push generated package to GitHub registry
        run: |
          dotnet nuget update source nakira974.github \
            --configfile ./NuGet.Config \
            --username nakira974 \
            --password ${{ secrets.NUGET_API_KEY }} \
            --store-password-in-clear-text
          dotnet nuget push D:\a\Lkhsoft.Dring\Lkhsoft.Dring\package\*.nupkg \
            --source nakira974.github \
            --skip-duplicate

      - name: Test
        run: dotnet test --no-build --verbosity normal