name: .NET

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore --configfile ./NuGet.Config
      - name: Build
        run: dotnet build --no-restore

      - name: Package nuget
        run: dotnet pack Lkhsoft.Dring.Shared\Lkhsoft.Dring.Shared.csproj --configuration release -o:package

      - name: Push generated package to GitHub registry
        run: |
          dotnet nuget update source nakira974.github --configfile ./NuGet.Config --username nakira974 --password ${{ secrets.GITHUB_TOKEN }}  --store-password-in-clear-text
          dotnet nuget push D:\a\Lkhsoft.Dring.Shared\Lkhsoft.Dring.Shared\package\*.nupkg --configfile ./NuGet.Config --source nakira974.github --skip-duplicate

      - name: Test
        run: dotnet test --no-build --verbosity normal